name: cml

on: [push, pull_request]

jobs: 
  industrial_ci: 
    strategy: 
      matrix:
        env:
          # Use custom Docker image 
          # TODO: Add UPSTREAM_WORKSPACE, DOCKER_PULL: true if public image, remove ROS_REPO? 
          - {BUILDER: catkin_make, DOCKER_IMAGE: luniaria/perceptionrunner}

    env:
      CCACHE_DIR: /github/home/.ccache
    
    runs-on: [self-hosted, gpu]
  
    steps: 
      - uses: actions/checkout@v2
        with: 
          repository: AscendNTNU/object_detector
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}

      - uses: actions/checkout@v2 
        with: 
          repository: AscendNTNU/close_module_tracking
          ssh-key: ${{ secrets.CLOSE_TRACKING_PULL_KEY }}
    
      - uses: actions/checkout@v2
        with: 
          repository: AscendNTNU/darknet
          ssh-key: ${{ secrets.DARKNET_PULL_KEY }}

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}










