name: PerceptionCI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: AscendNTNU/object_detector
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
          submodules: true 
      
      - uses: actions/checkout@v2
        with:  
          repository: AscendNTNU/close_module_tracking
          ssh-key: ${{ secrets.CLOSE_TRACKING_PULL_KEY }}
          submodules: true 
        
      - run: echo "-DENABLE_CUDA=OFF" >> $GITHUB_ENV
      
      - uses: actions/checkout@v2
        with:
          repository: AscendNTNU/darknet 
          ssh-key: ${{ secrets.DARKNET_PULL_KEY }}
          submodules: true 

        
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
